name: deploy
on:
  push:
  workflow_dispatch:

jobs:
  generate-algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: caibingcheng/hugo-algolia2@v1
        with:
          input: "./posts/**"
          output: "./algolia.json"
          index: ${{ secrets.ALGOlIA_INDEX }}
          apikey: ${{ secrets.ALGOlIA_APIKEY }}
          appid: ${{ secrets.ALGOlIA_APPID }}
